### ISSUE TITLE
プロジェクトページのURLに公開HTMLへのリンクを追加して欲しい

### ISSUE THREAD

**Issue by ongaeshi** [ayatakesi/emacs-24.5-doc-emacs#10]
大変便利に使わせてもらっています。
現状Googleで「emacs 24.5 マニュアル」などで検索するとこのGitHubトップがヒットしやすいので、

https://ayatakesi.github.io/emacs/24.5/emacs.html

へのリンクを https://github.com/ayatakesi/emacs-24.5-doc-emacs のURLに追加してもらえないでしょうか？

**Comment by ayatakesi** [comment]
了解いたしました、ありがとうございます。
いま出先なので、夜以降にで対応させていただきます。

**Comment by ayatakesi** [comment]
追加しました。ついでにREADME.mdにも追記しました。

**Comment by ongaeshi** [comment]
ありがとうございます :+1:
