### ISSUE TITLE
emacs-xtraのHTML,infoが作れない

### ISSUE THREAD

**Issue by osamu2001** [ayatakesi/emacs-24.5-doc-emacs#7]
READMEの手順でPDFが作れることは確認しました。

**Comment by ayatakesi** [comment]
emacs-xtra.texiに含まれる内容は、htmlとinfoに直接含まれます。texiの中でiftexとか使って出力がtex(pdf.ps含む)のときだけ2冊に分割してるようです

**Comment by osamu2001** [comment]
なるほど！
