### ISSUE TITLE
PDFにしおりが入らない

### ISSUE THREAD

**Issue by osamu2001** [ayatakesi/emacs-24.5-doc-emacs#8]
栞を入れるオプションが存在するのでしょうか？

**Comment by ayatakesi** [comment]
http://moimoitei.blogspot.com/2010/06/generate-pdf-with-bookmark-on.html
自分が参考にしたのは、上記サイトの『栞が入らない』の上の箇所までです。そこから下(texinfo.texとtxi-ja.texの準備)をすれば可能かも知れませぬ。

**Comment by ayatakesi** [comment]
ただ、この対応はemacs.texiの修正を要し、さらに
修正されたemacs.texiは、この対応をしたtexinfo.texiをユーザー側で用意しないといけなくなりそうなので、そこから先は試しておりませぬ
